FROM denoland/deno:alpine-2.9.4

WORKDIR /app

COPY deno.json deno.lock package.json ./
COPY index.js ./
RUN deno cache --frozen index.js

COPY . .

EXPOSE 3000

ENV HOST=0.0.0.0

CMD ["deno", "task", "start"]
