name: Test with Docker

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - run: docker build -t hello-hono .

      - run: docker run -d -p 3000:3000 hello-hono

      - name: Run the health check validation
        run: while ! curl -s 'http://localhost:3000/health' | grep 'OK'; do sleep 1; done
        timeout-minutes: 3
